#!/usr/bin/env python3
import paramiko
import time
import ipaddress

FWB_IP = "172.23.144.162"
SERVER_POOL = [ '10.2.0.172', '10.3.0.172',]
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect(FWB_IP, username="admin", password="fortinet")
command = ssh.invoke_shell()

def add_server_pool():
    command.send('config server-policy server-pool \n')
    for i in SERVER_POOL:
        command.send('edit ' + str(i) + '\n')
        command.send('config pserver-list \n')
        command.send('edit 1 \n')
        command.send('set ip ' + str(i) + '\n')
        command.send('end \n')
        command.send('next \n')
        time.sleep(0.2)
        print (command.recv(65535).decode('ascii'))
        # output = command.recv(65535).decode('ascii')
        # print (output)
    command.send('end \n')
    time.sleep(3)
    print (command.recv(65535).decode('ascii'))
    ssh.close()

add_server_pool()
